version: '3.9'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/rootroot
    ports:
      - 7474:7474
      - 7687:7687
